#!/bin/bash

# palava - a java-php-bridge
# Copyright (C) 2007  CosmoCode GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


CONFIG=../conf/palava.conf

# special config file?
if [ ! -z $1 ]; then
  CONFIG=$1
fi

# absolute path of config
cd `dirname $CONFIG`
CONFIG=`pwd`/`basename $CONFIG`

# config file exists?
if [ ! -f $CONFIG ]; then
  echo "Error:  config file not found ($CONFIG)"
  echo "Usage:  $0 <config file>"
  exit 1
fi

# load config
. $CONFIG

# build the classpath
if [ -d $PALAVA_DIR/classes/ ]; then
  PALAVA_CLASSPATH_CLASSES=`ls $PALAVA_DIR/classes/*.{jar,zip} 2>/dev/null | while read JAR; do
    PALAVA_CLASSPATH="$PALAVA_CLASSPATH:$JAR"
    echo $PALAVA_CLASSPATH
  done | tail -n 1`
fi

if [ -d $PALAVA_DIR/lib/ ]; then
  PALAVA_CLASSPATH_LIB=`ls $PALAVA_DIR/lib/*.{jar,zip} 2>/dev/null | while read JAR; do
    PALAVA_CLASSPATH="$PALAVA_CLASSPATH:$JAR"
    echo $PALAVA_CLASSPATH
  done | tail -n 1`
fi

PALAVA_CLASSPATH="$PALAVA_CLASSPATH_CLASSES:$PALAVA_CLASSPATH_LIB"


# start palava
cd $PALAVA_DIR
$JAVA_HOME/bin/java -Xms512m -Xmx512m -Djava.awt.headless=true -Dcom.mchange.v2.c3p0.cfg.xml=$PALAVA_DIR/conf/c3p0.xml -Dfile.encoding=UTF-8 -classpath $PALAVA_CLASSPATH de.cosmocode.palava.Loader $CONFIG $2
