#!/bin/bash

# palava - a java-php-bridge
# Copyright (C) 2007  CosmoCode GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

function printUsage {
  echo "Usage:  $0 <config file> [-p <port>] <option>"
  echo ""
  echo " options:"
  echo "   -e <code>    - execute the javascript code"
  echo "   -f <file>    - execute the file"
  exit 1
}


if [ -z $1 ]; then
  echo "Error:  you have to specify a config file!"
  printUsage
fi


CONFIG=$1
shift

# absolute path of config
cd `dirname $CONFIG`
CONFIG=`pwd`/`basename $CONFIG`

# config file exists?
if [ ! -f $CONFIG ]; then
  echo "Error:  config file not found!"
  printUsage
fi

# load config
. $CONFIG

# start palava
$JAVA_HOME/bin/java -Dfile.encoding=UTF-8 -classpath $PALAVA_DIR/classes/palava.jar de.cosmocode.palava.ClientBin $CONFIG $*
